---
title: AWS VPC Service Control Example
---
sequenceDiagram
    participant System
    participant WF

    note left of System: 承認依頼ボタン押下
    System->>+WF: シートＩＤ，副番、承認種類
    alt 承認
        WF-->>System: status=検認済
    else 却下
        WF-->>-System: status=作成中
    end 

    note left of System: 承認取消ボタン押下
    System->>+WF: 承認取消：
