from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.chat_completion_response_message_annotations_inner_url_citation import ChatCompletionResponseMessageAnnotationsInnerUrlCitation
from openapi_server import util

from openapi_server.models.chat_completion_response_message_annotations_inner_url_citation import ChatCompletionResponseMessageAnnotationsInnerUrlCitation  # noqa: E501

class ChatCompletionResponseMessageAnnotationsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, url_citation=None):  # noqa: E501
        """ChatCompletionResponseMessageAnnotationsInner - a model defined in OpenAPI

        :param type: The type of this ChatCompletionResponseMessageAnnotationsInner.  # noqa: E501
        :type type: str
        :param url_citation: The url_citation of this ChatCompletionResponseMessageAnnotationsInner.  # noqa: E501
        :type url_citation: ChatCompletionResponseMessageAnnotationsInnerUrlCitation
        """
        self.openapi_types = {
            'type': str,
            'url_citation': ChatCompletionResponseMessageAnnotationsInnerUrlCitation
        }

        self.attribute_map = {
            'type': 'type',
            'url_citation': 'url_citation'
        }

        self._type = type
        self._url_citation = url_citation

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionResponseMessageAnnotationsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionResponseMessage_annotations_inner of this ChatCompletionResponseMessageAnnotationsInner.  # noqa: E501
        :rtype: ChatCompletionResponseMessageAnnotationsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ChatCompletionResponseMessageAnnotationsInner.

        The type of the URL citation. Always `url_citation`.  # noqa: E501

        :return: The type of this ChatCompletionResponseMessageAnnotationsInner.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ChatCompletionResponseMessageAnnotationsInner.

        The type of the URL citation. Always `url_citation`.  # noqa: E501

        :param type: The type of this ChatCompletionResponseMessageAnnotationsInner.
        :type type: str
        """
        allowed_values = ["url_citation"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def url_citation(self) -> ChatCompletionResponseMessageAnnotationsInnerUrlCitation:
        """Gets the url_citation of this ChatCompletionResponseMessageAnnotationsInner.


        :return: The url_citation of this ChatCompletionResponseMessageAnnotationsInner.
        :rtype: ChatCompletionResponseMessageAnnotationsInnerUrlCitation
        """
        return self._url_citation

    @url_citation.setter
    def url_citation(self, url_citation: ChatCompletionResponseMessageAnnotationsInnerUrlCitation):
        """Sets the url_citation of this ChatCompletionResponseMessageAnnotationsInner.


        :param url_citation: The url_citation of this ChatCompletionResponseMessageAnnotationsInner.
        :type url_citation: ChatCompletionResponseMessageAnnotationsInnerUrlCitation
        """
        if url_citation is None:
            raise ValueError("Invalid value for `url_citation`, must not be `None`")  # noqa: E501

        self._url_citation = url_citation
