from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ChatCompletionDeleted(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, object=None, id=None, deleted=None):  # noqa: E501
        """ChatCompletionDeleted - a model defined in OpenAPI

        :param object: The object of this ChatCompletionDeleted.  # noqa: E501
        :type object: str
        :param id: The id of this ChatCompletionDeleted.  # noqa: E501
        :type id: str
        :param deleted: The deleted of this ChatCompletionDeleted.  # noqa: E501
        :type deleted: bool
        """
        self.openapi_types = {
            'object': str,
            'id': str,
            'deleted': bool
        }

        self.attribute_map = {
            'object': 'object',
            'id': 'id',
            'deleted': 'deleted'
        }

        self._object = object
        self._id = id
        self._deleted = deleted

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionDeleted':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionDeleted of this ChatCompletionDeleted.  # noqa: E501
        :rtype: ChatCompletionDeleted
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object(self) -> str:
        """Gets the object of this ChatCompletionDeleted.

        The type of object being deleted.  # noqa: E501

        :return: The object of this ChatCompletionDeleted.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object: str):
        """Sets the object of this ChatCompletionDeleted.

        The type of object being deleted.  # noqa: E501

        :param object: The object of this ChatCompletionDeleted.
        :type object: str
        """
        allowed_values = ["chat.completion.deleted"]  # noqa: E501
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def id(self) -> str:
        """Gets the id of this ChatCompletionDeleted.

        The ID of the chat completion that was deleted.  # noqa: E501

        :return: The id of this ChatCompletionDeleted.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ChatCompletionDeleted.

        The ID of the chat completion that was deleted.  # noqa: E501

        :param id: The id of this ChatCompletionDeleted.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def deleted(self) -> bool:
        """Gets the deleted of this ChatCompletionDeleted.

        Whether the chat completion was deleted.  # noqa: E501

        :return: The deleted of this ChatCompletionDeleted.
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: bool):
        """Sets the deleted of this ChatCompletionDeleted.

        Whether the chat completion was deleted.  # noqa: E501

        :param deleted: The deleted of this ChatCompletionDeleted.
        :type deleted: bool
        """
        if deleted is None:
            raise ValueError("Invalid value for `deleted`, must not be `None`")  # noqa: E501

        self._deleted = deleted
