from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ChatCompletionResponseMessageAnnotationsInnerUrlCitation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, end_index=None, start_index=None, url=None, title=None):  # noqa: E501
        """ChatCompletionResponseMessageAnnotationsInnerUrlCitation - a model defined in OpenAPI

        :param end_index: The end_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.  # noqa: E501
        :type end_index: int
        :param start_index: The start_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.  # noqa: E501
        :type start_index: int
        :param url: The url of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.  # noqa: E501
        :type url: str
        :param title: The title of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.  # noqa: E501
        :type title: str
        """
        self.openapi_types = {
            'end_index': int,
            'start_index': int,
            'url': str,
            'title': str
        }

        self.attribute_map = {
            'end_index': 'end_index',
            'start_index': 'start_index',
            'url': 'url',
            'title': 'title'
        }

        self._end_index = end_index
        self._start_index = start_index
        self._url = url
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionResponseMessageAnnotationsInnerUrlCitation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionResponseMessage_annotations_inner_url_citation of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.  # noqa: E501
        :rtype: ChatCompletionResponseMessageAnnotationsInnerUrlCitation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def end_index(self) -> int:
        """Gets the end_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The index of the last character of the URL citation in the message.  # noqa: E501

        :return: The end_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :rtype: int
        """
        return self._end_index

    @end_index.setter
    def end_index(self, end_index: int):
        """Sets the end_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The index of the last character of the URL citation in the message.  # noqa: E501

        :param end_index: The end_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :type end_index: int
        """
        if end_index is None:
            raise ValueError("Invalid value for `end_index`, must not be `None`")  # noqa: E501

        self._end_index = end_index

    @property
    def start_index(self) -> int:
        """Gets the start_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The index of the first character of the URL citation in the message.  # noqa: E501

        :return: The start_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :rtype: int
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index: int):
        """Sets the start_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The index of the first character of the URL citation in the message.  # noqa: E501

        :param start_index: The start_index of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :type start_index: int
        """
        if start_index is None:
            raise ValueError("Invalid value for `start_index`, must not be `None`")  # noqa: E501

        self._start_index = start_index

    @property
    def url(self) -> str:
        """Gets the url of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The URL of the web resource.  # noqa: E501

        :return: The url of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The URL of the web resource.  # noqa: E501

        :param url: The url of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def title(self) -> str:
        """Gets the title of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The title of the web resource.  # noqa: E501

        :return: The title of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.

        The title of the web resource.  # noqa: E501

        :param title: The title of this ChatCompletionResponseMessageAnnotationsInnerUrlCitation.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title
