from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.chat_completion_message_list_data_inner import ChatCompletionMessageListDataInner
from openapi_server import util

from openapi_server.models.chat_completion_message_list_data_inner import ChatCompletionMessageListDataInner  # noqa: E501

class ChatCompletionMessageList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, object='list', data=None, first_id=None, last_id=None, has_more=None):  # noqa: E501
        """ChatCompletionMessageList - a model defined in OpenAPI

        :param object: The object of this ChatCompletionMessageList.  # noqa: E501
        :type object: str
        :param data: The data of this ChatCompletionMessageList.  # noqa: E501
        :type data: List[ChatCompletionMessageListDataInner]
        :param first_id: The first_id of this ChatCompletionMessageList.  # noqa: E501
        :type first_id: str
        :param last_id: The last_id of this ChatCompletionMessageList.  # noqa: E501
        :type last_id: str
        :param has_more: The has_more of this ChatCompletionMessageList.  # noqa: E501
        :type has_more: bool
        """
        self.openapi_types = {
            'object': str,
            'data': List[ChatCompletionMessageListDataInner],
            'first_id': str,
            'last_id': str,
            'has_more': bool
        }

        self.attribute_map = {
            'object': 'object',
            'data': 'data',
            'first_id': 'first_id',
            'last_id': 'last_id',
            'has_more': 'has_more'
        }

        self._object = object
        self._data = data
        self._first_id = first_id
        self._last_id = last_id
        self._has_more = has_more

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionMessageList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionMessageList of this ChatCompletionMessageList.  # noqa: E501
        :rtype: ChatCompletionMessageList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object(self) -> str:
        """Gets the object of this ChatCompletionMessageList.

        The type of this object. It is always set to \"list\".   # noqa: E501

        :return: The object of this ChatCompletionMessageList.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object: str):
        """Sets the object of this ChatCompletionMessageList.

        The type of this object. It is always set to \"list\".   # noqa: E501

        :param object: The object of this ChatCompletionMessageList.
        :type object: str
        """
        allowed_values = ["list"]  # noqa: E501
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def data(self) -> List[ChatCompletionMessageListDataInner]:
        """Gets the data of this ChatCompletionMessageList.

        An array of chat completion message objects.   # noqa: E501

        :return: The data of this ChatCompletionMessageList.
        :rtype: List[ChatCompletionMessageListDataInner]
        """
        return self._data

    @data.setter
    def data(self, data: List[ChatCompletionMessageListDataInner]):
        """Sets the data of this ChatCompletionMessageList.

        An array of chat completion message objects.   # noqa: E501

        :param data: The data of this ChatCompletionMessageList.
        :type data: List[ChatCompletionMessageListDataInner]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def first_id(self) -> str:
        """Gets the first_id of this ChatCompletionMessageList.

        The identifier of the first chat message in the data array.  # noqa: E501

        :return: The first_id of this ChatCompletionMessageList.
        :rtype: str
        """
        return self._first_id

    @first_id.setter
    def first_id(self, first_id: str):
        """Sets the first_id of this ChatCompletionMessageList.

        The identifier of the first chat message in the data array.  # noqa: E501

        :param first_id: The first_id of this ChatCompletionMessageList.
        :type first_id: str
        """
        if first_id is None:
            raise ValueError("Invalid value for `first_id`, must not be `None`")  # noqa: E501

        self._first_id = first_id

    @property
    def last_id(self) -> str:
        """Gets the last_id of this ChatCompletionMessageList.

        The identifier of the last chat message in the data array.  # noqa: E501

        :return: The last_id of this ChatCompletionMessageList.
        :rtype: str
        """
        return self._last_id

    @last_id.setter
    def last_id(self, last_id: str):
        """Sets the last_id of this ChatCompletionMessageList.

        The identifier of the last chat message in the data array.  # noqa: E501

        :param last_id: The last_id of this ChatCompletionMessageList.
        :type last_id: str
        """
        if last_id is None:
            raise ValueError("Invalid value for `last_id`, must not be `None`")  # noqa: E501

        self._last_id = last_id

    @property
    def has_more(self) -> bool:
        """Gets the has_more of this ChatCompletionMessageList.

        Indicates whether there are more chat messages available.  # noqa: E501

        :return: The has_more of this ChatCompletionMessageList.
        :rtype: bool
        """
        return self._has_more

    @has_more.setter
    def has_more(self, has_more: bool):
        """Sets the has_more of this ChatCompletionMessageList.

        Indicates whether there are more chat messages available.  # noqa: E501

        :param has_more: The has_more of this ChatCompletionMessageList.
        :type has_more: bool
        """
        if has_more is None:
            raise ValueError("Invalid value for `has_more`, must not be `None`")  # noqa: E501

        self._has_more = has_more
