from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.chat_completion_request_message_content_part_file_file import ChatCompletionRequestMessageContentPartFileFile
from openapi_server import util

from openapi_server.models.chat_completion_request_message_content_part_file_file import ChatCompletionRequestMessageContentPartFileFile  # noqa: E501

class ChatCompletionRequestMessageContentPartFile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, file=None):  # noqa: E501
        """ChatCompletionRequestMessageContentPartFile - a model defined in OpenAPI

        :param type: The type of this ChatCompletionRequestMessageContentPartFile.  # noqa: E501
        :type type: str
        :param file: The file of this ChatCompletionRequestMessageContentPartFile.  # noqa: E501
        :type file: ChatCompletionRequestMessageContentPartFileFile
        """
        self.openapi_types = {
            'type': str,
            'file': ChatCompletionRequestMessageContentPartFileFile
        }

        self.attribute_map = {
            'type': 'type',
            'file': 'file'
        }

        self._type = type
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'ChatCompletionRequestMessageContentPartFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChatCompletionRequestMessageContentPartFile of this ChatCompletionRequestMessageContentPartFile.  # noqa: E501
        :rtype: ChatCompletionRequestMessageContentPartFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ChatCompletionRequestMessageContentPartFile.

        The type of the content part. Always `file`.  # noqa: E501

        :return: The type of this ChatCompletionRequestMessageContentPartFile.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ChatCompletionRequestMessageContentPartFile.

        The type of the content part. Always `file`.  # noqa: E501

        :param type: The type of this ChatCompletionRequestMessageContentPartFile.
        :type type: str
        """
        allowed_values = ["file"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def file(self) -> ChatCompletionRequestMessageContentPartFileFile:
        """Gets the file of this ChatCompletionRequestMessageContentPartFile.


        :return: The file of this ChatCompletionRequestMessageContentPartFile.
        :rtype: ChatCompletionRequestMessageContentPartFileFile
        """
        return self._file

    @file.setter
    def file(self, file: ChatCompletionRequestMessageContentPartFileFile):
        """Sets the file of this ChatCompletionRequestMessageContentPartFile.


        :param file: The file of this ChatCompletionRequestMessageContentPartFile.
        :type file: ChatCompletionRequestMessageContentPartFileFile
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file
