from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class WebSearchLocation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country=None, region=None, city=None, timezone=None):  # noqa: E501
        """WebSearchLocation - a model defined in OpenAPI

        :param country: The country of this WebSearchLocation.  # noqa: E501
        :type country: str
        :param region: The region of this WebSearchLocation.  # noqa: E501
        :type region: str
        :param city: The city of this WebSearchLocation.  # noqa: E501
        :type city: str
        :param timezone: The timezone of this WebSearchLocation.  # noqa: E501
        :type timezone: str
        """
        self.openapi_types = {
            'country': str,
            'region': str,
            'city': str,
            'timezone': str
        }

        self.attribute_map = {
            'country': 'country',
            'region': 'region',
            'city': 'city',
            'timezone': 'timezone'
        }

        self._country = country
        self._region = region
        self._city = city
        self._timezone = timezone

    @classmethod
    def from_dict(cls, dikt) -> 'WebSearchLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WebSearchLocation of this WebSearchLocation.  # noqa: E501
        :rtype: WebSearchLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country(self) -> str:
        """Gets the country of this WebSearchLocation.

        The two-letter  [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user, e.g. `US`.   # noqa: E501

        :return: The country of this WebSearchLocation.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this WebSearchLocation.

        The two-letter  [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user, e.g. `US`.   # noqa: E501

        :param country: The country of this WebSearchLocation.
        :type country: str
        """

        self._country = country

    @property
    def region(self) -> str:
        """Gets the region of this WebSearchLocation.

        Free text input for the region of the user, e.g. `California`.   # noqa: E501

        :return: The region of this WebSearchLocation.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region: str):
        """Sets the region of this WebSearchLocation.

        Free text input for the region of the user, e.g. `California`.   # noqa: E501

        :param region: The region of this WebSearchLocation.
        :type region: str
        """

        self._region = region

    @property
    def city(self) -> str:
        """Gets the city of this WebSearchLocation.

        Free text input for the city of the user, e.g. `San Francisco`.   # noqa: E501

        :return: The city of this WebSearchLocation.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this WebSearchLocation.

        Free text input for the city of the user, e.g. `San Francisco`.   # noqa: E501

        :param city: The city of this WebSearchLocation.
        :type city: str
        """

        self._city = city

    @property
    def timezone(self) -> str:
        """Gets the timezone of this WebSearchLocation.

        The [IANA timezone](https://timeapi.io/documentation/iana-timezones)  of the user, e.g. `America/Los_Angeles`.   # noqa: E501

        :return: The timezone of this WebSearchLocation.
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone: str):
        """Sets the timezone of this WebSearchLocation.

        The [IANA timezone](https://timeapi.io/documentation/iana-timezones)  of the user, e.g. `America/Los_Angeles`.   # noqa: E501

        :param timezone: The timezone of this WebSearchLocation.
        :type timezone: str
        """

        self._timezone = timezone
