from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.web_search_context_size import WebSearchContextSize
from openapi_server.models.web_search_user_location import WebSearchUserLocation
from openapi_server import util

from openapi_server.models.web_search_context_size import WebSearchContextSize  # noqa: E501
from openapi_server.models.web_search_user_location import WebSearchUserLocation  # noqa: E501

class WebSearch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_location=None, search_context_size=WebSearchContextSize.MEDIUM):  # noqa: E501
        """WebSearch - a model defined in OpenAPI

        :param user_location: The user_location of this WebSearch.  # noqa: E501
        :type user_location: WebSearchUserLocation
        :param search_context_size: The search_context_size of this WebSearch.  # noqa: E501
        :type search_context_size: WebSearchContextSize
        """
        self.openapi_types = {
            'user_location': WebSearchUserLocation,
            'search_context_size': WebSearchContextSize
        }

        self.attribute_map = {
            'user_location': 'user_location',
            'search_context_size': 'search_context_size'
        }

        self._user_location = user_location
        self._search_context_size = search_context_size

    @classmethod
    def from_dict(cls, dikt) -> 'WebSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Web_search of this WebSearch.  # noqa: E501
        :rtype: WebSearch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_location(self) -> WebSearchUserLocation:
        """Gets the user_location of this WebSearch.


        :return: The user_location of this WebSearch.
        :rtype: WebSearchUserLocation
        """
        return self._user_location

    @user_location.setter
    def user_location(self, user_location: WebSearchUserLocation):
        """Sets the user_location of this WebSearch.


        :param user_location: The user_location of this WebSearch.
        :type user_location: WebSearchUserLocation
        """

        self._user_location = user_location

    @property
    def search_context_size(self) -> WebSearchContextSize:
        """Gets the search_context_size of this WebSearch.


        :return: The search_context_size of this WebSearch.
        :rtype: WebSearchContextSize
        """
        return self._search_context_size

    @search_context_size.setter
    def search_context_size(self, search_context_size: WebSearchContextSize):
        """Sets the search_context_size of this WebSearch.


        :param search_context_size: The search_context_size of this WebSearch.
        :type search_context_size: WebSearchContextSize
        """

        self._search_context_size = search_context_size
