
alias dl='cloudshell download-files'
alias dt='cloudshell launch-tutorial -d'
alias edit='cloudshell edit-files'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias help='cat /home/sdkn104/README-cloudshell.txt'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias teachme='cloudshell launch-tutorial'

alias a=alias
alias gplm='(cd ~/misc; git pull origin master)'
alias gps='git push origin main'
alias so='source'
alias soo='source ~/misc/Linux/my.bashrc'
alias openai='export OPENAI_API_KEY=`gcloud secrets versions access latest --secret=openaikey`'
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''
alias x=''


